### PR TITLE
Add logging usage stats for longer running commands

### PR DESCRIPTION
**Pull request by richardmiller**

### CODE REVIEW

**Comment by richardmiller** [comment]
This isn't that useful yet as the long running part of the build command is CP building the remote environment but the build command doesn't wait for that to happen. Will make more sense with #6 in place.

**Comment by tonypiper** [comment]
Awesome - even being able to see the number of times a command is being used (without the duration for the long-running tasks) will be useful in determining if we have stability problems.

**Comment by richardmiller** [comment]
Yes, although rebuilding the envs is not necessarily a sign of instability but something that needs doing when you change branch and don't want to just sync the files, so if there are a lot of changes or dependencies needs updating or migrations running.

**Comment by sroze** [comment]
Closed in favor of #19

**Pull request closed without merging**
